#!/bin/bash
# Sources:
# - Main Script:
#       http://www.2600.com/code/252/mac-address-changer/mac-address-changer.sh.txt
# - Initial MAC Configuration:
#       http://community.spiceworks.com/scripts/show/770-change-your-mac-address
# - Random MAC generator:
#       http://www.commandlinefu.com/commands/view/745/generat-a-random-mac-address
# This script allows you to change your MAC address. Proper
# syntax is as follows:

# chmac home <interface>       # Changes MAC Address to Original
# chmac <MAC> <interface>      # Changes MAC Address to One Specified
# chmac random <interface>     # Changes MAC Address Randomly

# Default interface
iface="wlan0"

if [ $# -eq 2 ]; then
    iface=$2
fi

file=$HOME/.mac.conf
if [ ! -f $file ] ; then
    echo "File $file Does Not Exist"
    echo "Creating file..."
    omac=$(ifconfig $iface | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
    echo $omac > $file
    echo "File created with MAC: $omac"
else
    omac=$(cat $file)
fi

if [ "$1" == home ]; then
    sudo ifconfig $iface down
    sudo ifconfig $iface hw ether $omac
    sudo ifconfig $iface up
    echo "Original MAC Address Restored."
    exit 0
elif [ "$1" == random ]; then
    # First bit explanation: http://packetsdropped.wordpress.com/2011/01/13/mac-address-universally-or-locally-administered-bit-and-individualgroup-bit/
    rmac=f8:`(date; cat /proc/interrupts) | md5sum | sed -r 's/^(.{10}).*$/\1/; s/([0-9a-f]{2})/\1:/g; s/:$//;'`
    sudo ifconfig $iface down
    sudo ifconfig $iface hw ether $rmac
    sudo ifconfig $iface up
    echo "MAC Address Randomly Changed To $rmac"
    exit 1
elif [ "$1" ]; then
    sudo ifconfig eth0 down
    sudo ifconfig eth0 hw ether $1
    sudo ifconfig eth0 up
    echo "MAC Address Changed To $1."
    exit 2
else
    echo "chmac home (<interface>)      # Changes MAC Address to Original"
    echo "chmac <MAC> (<interface>)     # Changes MAC Address to One Specified"
    echo "chmac random (<interface>)    # Changes MAC Address Randomly"
    exit 3
fi
